name: happyn_mobile
description: Happyn mobile application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^11.0.0
  geolocator: ^14.0.3
  google_fonts: ^8.2.1
  http: ^1.6.0
  maplibre_gl: ^0.27.0
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
